# Kurzeinführung / Python
## Allgemeines

In [1]:
import numpy as np
import pandas as pd
from numpy import sqrt
from pandas import Series, DataFrame

In [2]:
print("Hallo Welt")

Hallo Welt


In [3]:
a = 3
b = 4
a + b

7

In [4]:
c, d = 5,6
c + d

11

In [5]:
np.sqrt(2)

1.4142135623730951

In [6]:
sqrt(2)

1.4142135623730951

## Numpy
`Numpy` = `(Numerical Python)` 

In [7]:
x = np.array([2, 1, 4, 5, -8])
x

array([ 2,  1,  4,  5, -8])

In [8]:
3*x

array([  6,   3,  12,  15, -24])

In [9]:
x*x

array([ 4,  1, 16, 25, 64])

In [10]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.arange(start=1, stop=7)

array([1, 2, 3, 4, 5, 6])

In [12]:
np.arange(start=1, stop=7, step=.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [13]:
# der Parameter stop ist nicht der letzte Wert, sondern der Wert davor!
z = np.arange(2,9)
print(z)
z = np.arange(start=2, stop=9)
print(z)

[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]


## Pandas

In [14]:
temp_LU = Series([1, 5, 9, 15, 20, 25, 25])
temp_LU

0     1
1     5
2     9
3    15
4    20
5    25
6    25
dtype: int64

In [15]:
for temp in temp_LU:
    print(temp)

1
5
9
15
20
25
25


In [16]:
temp_LU[2]

9

In [17]:
temp_LU2 = Series([1, 5, 9, 15, 20, 25, 25], index=("jan", "feb", "mar", "apr", "mai", "jun", "jul"))
temp_LU2

jan     1
feb     5
mar     9
apr    15
mai    20
jun    25
jul    25
dtype: int64

In [18]:
temp_LU2["mar"]

9

In [19]:
temp_LU2.index

Index(['jan', 'feb', 'mar', 'apr', 'mai', 'jun', 'jul'], dtype='object')

In [20]:
temp_LU.mean()

14.285714285714286

In [21]:
temp_LU2.var()

92.23809523809524

In [22]:
temp_LU2.std()

9.60406659900353

In [23]:
temp_CH = DataFrame({
    "Luzern": ([1,5,9,15,20,25,25]),
    "Basel": ([3,4,12,16,18,23,32]),
    "Zuerich": ([8,6,10,17,23,22,24])},
    index=["jan","feb","mar","apr","mai","jun","jul"]
)

temp_CH

Basel  Luzern  Zuerich
jan      3       1        8
feb      4       5        6
mar     12       9       10
apr     16      15       17
mai     18      20       23
jun     23      25       22
jul     32      25       24

In [24]:
temp_CH.columns

Index(['Basel', 'Luzern', 'Zuerich'], dtype='object')

In [25]:
temp_CH.mean()

Basel      15.428571
Luzern     14.285714
Zuerich    15.714286
dtype: float64

In [26]:
temp_CH.mean(axis=1)

jan     4.000000
feb     5.000000
mar    10.333333
apr    16.000000
mai    20.333333
jun    23.333333
jul    27.000000
dtype: float64

In [27]:
temp_CH.min(axis=1)

jan     1
feb     4
mar     9
apr    15
mai    18
jun    22
jul    24
dtype: int64

In [28]:
temp_CH.max(axis=1)

jan     8
feb     6
mar    12
apr    17
mai    23
jun    25
jul    32
dtype: int64

In [29]:
# nur eine Spalte beachten
temp_CH["Luzern"]

jan     1
feb     5
mar     9
apr    15
mai    20
jun    25
jul    25
Name: Luzern, dtype: int64

In [30]:
# Der alleinstehende : als 1. Argument soll andeuten,
# dass alle Zeilen gemeint sind.
temp_CH.loc[:,"Luzern"]

jan     1
feb     5
mar     9
apr    15
mai    20
jun    25
jul    25
Name: Luzern, dtype: int64

In [31]:
# Der : als 1. Argument hat die Bedeutung von . . . bis.
temp_CH.loc["jan":"mar","Luzern"]

jan    1
feb    5
mar    9
Name: Luzern, dtype: int64

In [32]:
temp_CH.loc[["mai","jul"],["Basel","Zuerich"]]

Basel  Zuerich
mai     18       23
jul     32       24