# Allgemeines

In [3]:
print("Hello world!")

Hello world!


In [6]:
a = 3
b = 4

a + b
## solution: 7

7

In [10]:
a, b = 3, 4

a + b
## solution: 7

7

In [12]:
import numpy as np
np.sqrt(2)

## solution: 1.4142135623730951

1.4142135623730951

In [14]:
from numpy import sqrt
sqrt(2)

## solution: 1.4142135623730951

1.4142135623730951

In [16]:
from numpy import *
sqrt(2)

## Bad solution, because there are more then one function with the same name
## ==> as example numpy.sqrt and sympy.sqrt
## solution: 1.4142135623730951

1.4142135623730951

# numpy (Numerical Python)

## Vector

In [18]:
import numpy as np

x = np.array([2,1,4,5,-8])

x

array([ 2,  1,  4,  5, -8])

In [19]:
3*x

array([  6,   3,  12,  15, -24])

In [21]:
x*x

array([ 4,  1, 16, 25, 64])

In [26]:
x = np.linspace(start=1, stop=2, num=4)
x

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [29]:
y = np.arange(start=1, stop=7, step=0.5)
y

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [31]:
z = np.arange(2,9)
z
## the stop value is not contain in the vector!

array([2, 3, 4, 5, 6, 7, 8])

In [32]:
w = np.arange(9)
w
## the list starts in python with 0!

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Pandas

In [37]:
import pandas as pd
from pandas import Series, DataFrame

temp_lu = Series([1, 5, 9, 15, 20, 25, 25])

temp_lu

0     1
1     5
2     9
3    15
4    20
5    25
6    25
dtype: int64

In [38]:
temp_lu[2]
# 6

9